/*
 * FigurePanel.java
 *
 * Created on Saturday, 19, March 2005, 12:36
 */

package fem.divider.figure;

import java.awt.*;
import java.awt.event.*;
//import java.awt.geom.*;

/**
 *
 * @author  gefox
 */
public class FigurePanel extends fem.divider.AbstractPanel {

		/** Creates new form FigurePanel */
    public FigurePanel(Figure fig, fem.divider.RectangleArea world_) {
				super(world_);
				figure = fig;
				figure.setPanel(this);
				
//        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents

		public void draw(Graphics2D g2)
		{
//				Rectangle2D rect = new Rectangle2D.Double(xs(25), ys(75), ws(50), hs(50) );
//				g2.draw(rect);
				figure.draw(g2);
		}
		
		
		public void mouseClicked(MouseEvent event)
		{
//				System.out.println("clicked");
		}
		
    public void mousePressed(MouseEvent e)
		{
				if(e.isPopupTrigger()&&figure.isEditable() )
				{
						popup(e);
				}
		}

    public void mouseReleased(MouseEvent e) 
		{
				if(e.isPopupTrigger() )
				{
						popup(e);
				}
		}
	
		/**
		 *Shows popup menu
		 */
		public void popup(MouseEvent e)
		{
				double x = xw(e.getX());
				double y = yw(e.getY());
				double handle = ww(HANDLE_WIDTH);
				
				Segment segment = figure.findSegment(xw(e.getX()), yw(e.getY()), ww(HANDLE_WIDTH));
				if(segment == null) return;
				Node node = segment.findNode(x, y, handle);
				if(node == null) 
						segment.popupMenu.show(drawingPanel, e.getX(), e.getY());
				else
				{
						node.popupMenu.show(drawingPanel, e.getX(), e.getY());
				}
		}
		
		public void setFigure(Figure fig)
		{
				figure = fig;
				figure.setPanel(this);
		}
		
		public Figure getFigure()
		{
				return figure;
		}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

		Figure figure;
}
